### ISSUE TITLE
Application Launcher: "Applications" icon in new is bigger than "primary actions" icons

### ISSUE THREAD

**Issue by xfzv** [pwyde/monochrome-kde#2]
![screenshot](https://user-images.githubusercontent.com/78810647/111311370-0f7b9980-8656-11eb-961a-8213d225c458.png)

Or maybe it's intended?

**Comment by pwyde** [comment]
Fixed in commit 8086397.

**Comment by xfzv** [comment]
![Screenshot-2021-03-16T23:20:09](https://user-images.githubusercontent.com/78810647/111387562-d1a66180-86a5-11eb-928b-8a1031699be6.png)

Awesome! thank you.
