### ISSUE TITLE
VirtualBox Manager looks bad when using any Monochrome variant with Kvantum

### ISSUE THREAD

**Issue by xfzv** [pwyde/monochrome-kde#3]
OS : Arch Linux

```
kvantummanager --version
Kvantum Manager 0.19.0
```

- Without any Kvantum theme:

![without_kvantum](https://user-images.githubusercontent.com/78810647/111311936-afd1be00-8656-11eb-8fdf-83ebcb1d7548.png)

- With `MonochromeSolid` applied in Kvantum:

![kvantum_MonochromeSolid](https://user-images.githubusercontent.com/78810647/111311933-af392780-8656-11eb-9306-630242919c3a.png)

- With `GnomeDark` theme applied in Kvantum:
![kvantum_GnomeDark](https://user-images.githubusercontent.com/78810647/111311930-aea09100-8656-11eb-8145-dee2ffa7df83.png)

Is there any workaround? this is the only program which doesn't look good on my system with Monochrome.

**Comment by pwyde** [comment]
Unfortunately this is nothing I can do about without screwing up the color scheme in the rest of the theme. I believe this is the way that VirtualBox is rendering the colors in the theme and it appears to be hard coded.

One thought I had was to exclude this particular application from being themed by Kvantum. Problem is that you apply the theme engine (application style) for the majority of Plasma/Qt interface. I have not seen a way to use Breeze engine for application X and Kvantum for application Y.

You could select a Kvantum theme that looks better in VirtualBox and use only that specific theme for VirtualBox: **Kvantum Manager** > **Application Themes**. This however makes the user interface inconsistent 😞

I personally hate inconsistent user interfaces so this frustrates me. I do not use VirtualBox myself so I had no idea that Monochrome theme looked like this. I tested with a couple of other Kvantum themes and in my opinion they did not look any better. I will not mention them out of respect for the creators of those themes, but it shows me that there is a general issue with how VirtualBox renders themes using the Kvantum engine. Sorry...

**Comment by xfzv** [comment]
Yes, VirtualBox has always been a PITA as far as theming goes, at least from my experience.

It's not rendering that bad with Monochrome anyway, it's not as if text was unreadable for instance. I can totally live with it.

Keep up the good work!
