### ISSUE TITLE
Context menus need borders or white shadows

### ISSUE THREAD

**Issue by CarterSnich** [pwyde/monochrome-kde#5]
Context menus need borders or white shadows to distinguish from other UI elements. Or is it just me not applying the theme properly?

![image](https://user-images.githubusercontent.com/52433531/235645960-0fccea00-7517-4d67-b4fa-b237a60a2182.png)

**Comment by pwyde** [comment]
I am not able to re-produce your issue, sorry.

Could it be that you have disabled all drop-shadows somehow?

**Comment by CarterSnich** [comment]
I don't remember any. Where can I enable it back on?

**Comment by pwyde** [comment]
The thing that is missing in your screenshot is all the shadows for menus. This is how it looks on my test system:
![image](https://github.com/pwyde/monochrome-kde/assets/34695534/2c89d9c9-83e8-42e4-b152-278c834e5c3e)
As you can see, the shadow for every menu and sub-menu make them more distinguishable.

Take a look in **Kvantum Manager** > Configure Active Theme > Compositing & General Look. See if **Shadowless menus and tooltips** is enabled:
![image](https://github.com/pwyde/monochrome-kde/assets/34695534/fecaa37c-8fb3-4a5f-bb7b-f5a3c11adb7b)

**Comment by pwyde** [comment]
Check if **Shadowless menus and tooltips** is enabled in **Kvantum Manager**.
